# Aerospike database configuration file for Data Masking Demo

service {
	feature-key-file /etc/aerospike/features.conf
	cluster-name docker
}

# Just having this security stanza enables security in Aerospike 8.x
security {
}

logging {
	file /var/log/aerospike/aerospike.log {
		context any info
	}

	file /var/log/aerospike/audit.log {
		context audit info
	}

	console {
		context any info
	}
}

network {
	service {
		address any
		port 3000
	}

	heartbeat {
		mode mesh
		address local
		port 3002
		interval 150
		timeout 10
	}

	fabric {
		address local
		port 3001
	}
}

namespace test {
	replication-factor 1

	storage-engine device {
		file /opt/aerospike/data/test.dat
		filesize 4G
		read-page-cache true
	}
}
